# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: giacomop
app: ${file(../serverless-global.yml):app}
service: ${self:app}-s3

custom:
  gipcerName: "gip-cer-bills-bucket-${sls:stage}"

provider:
  name: aws
  region: eu-central-1
  profile: SAID
  environment:
    BUCKET_NAME: ${self:custom.gipcerName}

functions:
  gipCerBillsHandler:
    handler: app.handler
    reservedConcurrency: 3
    memorySize: 1024
    timeout: 30
    events:
      - s3:
          bucket: ${self:custom.gipcerName}
          event: s3:ObjectCreated:*
          existing: true
    iamRoleStatements:
      - Effect: Allow
        Action:
          - s3:GetObject
          - s3:PutObject
        Resource:
          - "arn:aws:s3:::${self:custom.gipcerName}"
          - "arn:aws:s3:::${self:custom.gipcerName}/*"


resources:
  Resources:
    gipCerBillsBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.gipcerName}

plugins:
  - serverless-iam-roles-per-function