app: ${file(../serverless-global.yml):app}
service: ${self:app}-s3

frameworkVersion: "3"

custom:
  gipcerName: "gip-cer-bucket-${sls:stage}"

provider:
  name: aws
  region: eu-central-1
  profile: SAID

resources:
  Resources:
    gipcerBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.gipcerName}